@cartBaseUrl = http://localhost:3002
@orderBaseUrl = http://localhost:3003
@userId = 1
@idempotencyKey = checkout-{{$timestamp}}

### 1) Get cart
GET {{cartBaseUrl}}/cart
x-user-id: {{userId}}

### 2) Add first item to cart
POST {{cartBaseUrl}}/cart/items
Content-Type: application/json
x-user-id: {{userId}}

{
  "productId": 101,
  "name": "Acme Hoodie",
  "price": 62,
  "quantity": 1
}

### 3) Add second item to cart
POST {{cartBaseUrl}}/cart/items
Content-Type: application/json
x-user-id: {{userId}}

{
  "productId": 102,
  "name": "Acme Mug",
  "price": 16,
  "quantity": 2
}

### 4) Checkout order
POST {{orderBaseUrl}}/orders
Content-Type: application/json
x-user-id: {{userId}}
idempotency-key: {{idempotencyKey}}

{
  "note": "Ship in office hours"
}

### 5) Retry same checkout with same idempotency key (should return same order)
POST {{orderBaseUrl}}/orders
Content-Type: application/json
x-user-id: {{userId}}
idempotency-key: {{idempotencyKey}}

{
  "note": "Ship in office hours"
}

### 6) List my orders
GET {{orderBaseUrl}}/orders
x-user-id: {{userId}}

### 7) Cart should be cleared after checkout
GET {{cartBaseUrl}}/cart
x-user-id: {{userId}}
