import { cookies } from "next/headers";
import { fetchAdminNotificationDetail, fetchAdminNotifications } from "@/lib/admin/api";
import { ADMIN_SESSION_COOKIE } from "@/lib/admin/constants";
import { AdminDataTable } from "@/components/ui/AdminDataTable";
import { StatusBadge } from "@/components/ui/StatusBadge";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;

function readParam(params: Record<string, string | string[] | undefined>, key: string) {
  const value = params[key];
  return Array.isArray(value) ? value[0] : value;
}

export default async function AdminNotificationsPage({ searchParams }: { searchParams: SearchParams }) {
  const cookieStore = await cookies();
  const token = cookieStore.get(ADMIN_SESSION_COOKIE)?.value || "";
  const params = await searchParams;
  const search = readParam(params, "search");
  const type = readParam(params, "type");
  const selected = readParam(params, "selected");
  const response = await fetchAdminNotifications(token, {
    search,
    type: type ?? undefined,
  }).catch(() => ({ items: [], total: 0 }));
  const selectedItem =
    selected ? await fetchAdminNotificationDetail(token, selected).catch(() => null) : null;

  return (
    <div className="space-y-6">
      <div>
        <p className="text-xs font-bold uppercase tracking-[0.18em] text-admin-muted">System</p>
        <h1 className="mt-2 text-3xl font-black tracking-tight text-admin-text">Notifications</h1>
        <p className="mt-2 text-sm text-admin-muted">
          Review notification delivery history generated by payment and inventory outcomes.
        </p>
      </div>

      <form className="admin-surface grid gap-3 p-4 md:grid-cols-[minmax(0,1fr)_220px_auto]" action="/admin/notifications">
        <input
          name="search"
          defaultValue={search ?? ""}
          placeholder="Search order id, recipient, or message..."
          className="rounded-lg border border-admin-border bg-white px-3 py-2 text-sm text-admin-text outline-none focus:border-admin-accent"
        />
        <input
          name="type"
          defaultValue={type ?? ""}
          placeholder="Filter by type"
          className="rounded-lg border border-admin-border bg-white px-3 py-2 text-sm text-admin-text outline-none focus:border-admin-accent"
        />
        <button className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white">Filter</button>
      </form>

      <section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
        <AdminDataTable
          rows={response.items}
          getRowKey={(item) => item.id}
          emptyTitle="No notifications found"
          emptyDescription="Notification history will appear here after asynchronous events are published."
          columns={[
            { key: "order", header: "Order", render: (item) => item.orderId },
            { key: "type", header: "Type", render: (item) => item.type },
            {
              key: "status",
              header: "Status",
              render: (item) => <StatusBadge tone={item.status === "sent" ? "success" : "warning"}>{item.status}</StatusBadge>,
            },
            { key: "recipient", header: "Recipient", render: (item) => item.recipient ?? "Unassigned" },
            {
              key: "detail",
              header: "Detail",
              className: "text-right",
              render: (item) => (
                <a href={`/admin/notifications?selected=${item.id}`} className="font-bold text-admin-accent">
                  Review
                </a>
              ),
            },
          ]}
        />

        <aside className="admin-surface h-fit p-5">
          <h2 className="text-lg font-black text-admin-text">Notification detail</h2>
          {selectedItem ? (
            <div className="mt-4 space-y-3 text-sm text-admin-text">
              <p><span className="font-bold">Order:</span> {selectedItem.orderId}</p>
              <p><span className="font-bold">Type:</span> {selectedItem.type}</p>
              <p><span className="font-bold">Recipient:</span> {selectedItem.recipient ?? "Unavailable"}</p>
              <p><span className="font-bold">Message:</span> {selectedItem.message ?? "No message body"}</p>
              <p><span className="font-bold">Created:</span> {new Date(selectedItem.createdAt).toLocaleString()}</p>
            </div>
          ) : (
            <p className="mt-4 text-sm text-admin-muted">Select a notification to inspect the delivery record.</p>
          )}
        </aside>
      </section>
    </div>
  );
}
