import { Module } from '@nestjs/common';
import {
  AuthController,
  UserController,
  SellerController,
  SellerShopController,
  PublicShopsController,
  ProductController,
  CategoryController,
  AdminProductController,
  AdminCategoryController,
  AdminOrderController,
  AdminBranchController,
  AdminCartController,
  AdminNotificationController,
  AdminPaymentController,
  AdminStoreSettingsController,
  OrderController,
  CartController,
  InventoryController,
  AdminInventoryController,
  AdminUserController,
  AdminSellerProfilesController,
  PaymentController,
  NotificationController,
  StoreSettingsController,
  AdminShopsController,
  AIController,
  SellerProductsProxyController,
  AdminProductModerationProxyController,
  ShopProductsProxyController,
  SellerInventoryProxyController,
  SellerOrderProxyController,
  AdminShopOrderProxyController,
} from './v1/routes.controller';
import { ProxyModule } from '../proxy/proxy.module';

@Module({
  imports: [ProxyModule],
  controllers: [
    AuthController,
    UserController,
    SellerController,
    SellerShopController,
    PublicShopsController,
    ProductController,
    CategoryController,
    AdminProductController,
    AdminCategoryController,
    AdminOrderController,
    AdminBranchController,
    AdminCartController,
    OrderController,
    CartController,
    InventoryController,
    AdminInventoryController,
    AdminUserController,
    AdminSellerProfilesController,
    AdminNotificationController,
    AdminPaymentController,
    AdminStoreSettingsController,
    PaymentController,
    NotificationController,
    StoreSettingsController,
    AdminShopsController,
    AIController,
    SellerProductsProxyController,
    AdminProductModerationProxyController,
    ShopProductsProxyController,
    SellerInventoryProxyController,
    SellerOrderProxyController,
    AdminShopOrderProxyController,
  ],
})
export class RoutesModule {}
